### ISSUE TITLE
TypeError: req.isAuthenticated is not a function

### ISSUE THREAD

**Issue by ForSomeCodezYT** [InsiderJanggo/azunyan#4]
TypeError: req.isAuthenticated is not a function 
    at CheckAuth (H:\Codes\Projects\azunyan\website\dashboard.js:136:11)
    at Layer.handle [as handle_request] (H:\Codes\Projects\azunyan\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\Codes\Projects\azunyan\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\Codes\Projects\azunyan\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (H:\Codes\Projects\azunyan\node_modules\express\lib\router\layer.js:95:5)
    at H:\Codes\Projects\azunyan\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (H:\Codes\Projects\azunyan\node_modules\express\lib\router\index.js:335:12)
    at next (H:\Codes\Projects\azunyan\node_modules\express\lib\router\index.js:275:10)
    at SessionStrategy.strategy.pass (H:\Codes\Projects\azunyan\node_modules\passport\lib\middleware\authenticate.js:343:9)
    at H:\Codes\Projects\azunyan\node_modules\passport\lib\strategies\session.js:69:12
    at pass (H:\Codes\Projects\azunyan\node_modules\passport\lib\authenticator.js:337:31)
    at deserialized (H:\Codes\Projects\azunyan\node_modules\passport\lib\authenticator.js:349:7)
    at H:\Codes\Projects\azunyan\website\dashboard.js:15:3
    at pass (H:\Codes\Projects\azunyan\node_modules\passport\lib\authenticator.js:357:9)
    at Authenticator.deserializeUser (H:\Codes\Projects\azunyan\node_modules\passport\lib\authenticator.js:362:5)
    at SessionStrategy.authenticate (H:\Codes\Projects\azunyan\node_modules\passport\lib\strategies\session.js:60:10)

**Comment by RaymondJiang1** [comment]
Hey! FYI, this bot is in development, so we do expect bugs. I do not know when this github repo will be completed but I will look into the issue. Please be patient!

**Comment by Wilbert-mad** [comment]
For this I have fixed, please expect an update from me.

**Comment by RaymondJiang1** [comment]
Ok!

**Comment by InsiderJanggo** [comment]
im sorry for the rate reply i will merge your pull request

**Comment by Wilbert-mad** [comment]
Na you're good :)

**Comment by RaymondJiang1** [comment]
:)

**Comment by RaymondJiang1** [comment]
I think I am able to close this? I'll let @InsiderJanggo close it 👍
